name: Catalog Pull and Commit (Test, Multi-branch)

on:
  workflow_dispatch: {}

  push:
    branches:
      - main   # whenever you push to main, this runs for every catalog-* branch

  schedule:
    - cron: "0 2 * * *" # optional: daily at 02:00 UTC

jobs:
  pull-and-commit:
    runs-on: ubuntu-latest

    permissions:
      contents: write
      pull-requests: write

    strategy:
      matrix:
        catalog_branch:
          - catalog-main
          - catalog-sandbox
          - catalog-sources
          - catalog-config

    steps:
      - name: Checkout catalog branch
        uses: actions/checkout@v4
        with:
          ref: ${{ matrix.catalog_branch }}
          fetch-depth: 0    # required for commits

      - name: Set up Git user
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          if [ -f requirements.txt ]; then
            python -m pip install --upgrade pip
            pip install -r requirements.txt
          fi

      # ---------------------------------------------------------
      #   ðŸ”§ Normal file creation (simulated pull)
      # ---------------------------------------------------------
      - name: Simulate catalog pull (create test file)
        run: |
          echo "Running test file creation for branch: ${{ matrix.catalog_branch }}"
          mkdir -p tests/output
          echo "This is a test run for branch: ${{ matrix.catalog_branch }}" > tests/output/testfile_${{ matrix.catalog_branch }}_$(date +'%Y%m%d-%H%M%S').txt
          cat tests/output/*.txt

      # ---------------------------------------------------------
      #   â­ Branch-Specific Logic: catalog-sandbox only
      # ---------------------------------------------------------
      - name: Promote content (sandbox only)
        if: matrix.catalog_branch == 'catalog-sandbox'
        run: |
          echo "Running promote.command for catalog-sandbox..."
          echo "Contents are promoted."

      # ---------------------------------------------------------
      #   ðŸ” Git detection
      # ---------------------------------------------------------
      - name: Check for changes
        id: git_status
        run: |
          if [[ -n "$(git status --porcelain)" ]]; then
            echo "changes=true" >> $GITHUB_OUTPUT
          else
            echo "changes=false" >> $GITHUB_OUTPUT
          fi

      # ---------------------------------------------------------
      #   ðŸ“ Commit changes
      # ---------------------------------------------------------
      - name: Commit and push changes
        if: steps.git_status.outputs.changes == 'true'
        run: |
          ID=$(date +'%Y%m%d-%H%M%S')
          COMMIT_MSG="Catalog sync test commit (${{ matrix.catalog_branch }}) - ID:$ID"
          echo "Committing changes: $COMMIT_MSG"
          git add .
          git commit -m "$COMMIT_MSG"
          git push origin ${{ matrix.catalog_branch }}

      - name: No changes detected
        if: steps.git_status.outputs.changes == 'false'
        run: echo "No changes to commit for ${{ matrix.catalog_branch }}."

      # ---------------------------------------------------------
      #   ðŸ§© Create PR from catalog-sandbox â†’ catalog-main
      #   Runs only for catalog-sandbox, after push
      # ---------------------------------------------------------
      - name: Create PR to catalog-main (sandbox only)
        if: matrix.catalog_branch == 'catalog-sandbox'
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const base = 'catalog-main';
            const head = 'catalog-sandbox';
            const title = 'Promote from catalog-sandbox to catalog-main';
            const body = 'Automated promotion PR from catalog-sandbox to catalog-main.';

            const owner = context.repo.owner;
            const repo = context.repo.repo;

            // Check if an open PR already exists from sandbox -> main
            const existing = await github.rest.pulls.list({
              owner,
              repo,
              state: 'open',
              head: `${owner}:${head}`,
              base,
            });

            if (existing.data.length > 0) {
              core.info(`Open PR already exists from ${head} to ${base}: #${existing.data[0].number}`);
            } else {
              const pr = await github.rest.pulls.create({
                owner,
                repo,
                title,
                head,
                base,
                body,
              });
              core.info(`Created PR #${pr.data.number} from ${head} to ${base}`);
            }