name: Deploy Project
on:
  push:
    branches:
      - main
      - sandbox
      - dev-*
    paths-ignore:
      - .github/workflows/*
  workflow_dispatch:
  pull_request:
    types: [opened] # Activity type
jobs:
  test:
#    continue-on-error: true
    runs-on: ubuntu-latest
    environment: testing
    env:
      MY_SECRET: ${{ secrets.MY_SECRET }}
    steps:
      - name: Get code
        uses: actions/checkout@v3
      - name: Install NodeJS
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Cache dependencies
        id: cache
        uses: actions/cache@v3
        with:
          path: |
            ~/.npm
          key: deps-node-modules-${{ hashFiles('**/package-lock.json') }}
      - name: Install dependencies
        if: steps.cache.outputs.cache-hit != 'true'
        run: |
          npm ci
          echo "My secret value is:  ${{ env.MY_SECRET}}"
      - name: Run tests
        id: run-tests
        run: npm test
      - name: Upload Test Report
        if: failure() && steps.run-tests.outcome == 'failure'
        uses: actions/upload-artifact@v4
        with:
          name: test-report
          path: test.json
  build:
    needs: test
    runs-on: ubuntu-latest
    outputs:
      script-file: ${{ steps.publish.outputs.script-file }}
    steps:
      - name: Get code
        uses: actions/checkout@v3
      - name: Install NodeJS
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Cache dependencies
        uses: actions/cache@v3
        with:
          path: |
            ~/.npm
          key: deps-node-modules-${{ hashFiles('**/package-lock.json') }}
      - name: Install dependencies
        run: npm ci
      - name: Build project
        run: npm run build
      - name: Publish JS file
        id: publish
        run: find dist/assets/*.js -type f -execdir echo '::set-output name=script-file::{}' ';'
        #run: find dist/assets/*.js -type f -execdir echo 'script-file={}' >> $GITHUB_OUTPUT ';'
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: dist-files
          path: dist

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - name: Deploy
      run: echo "Deploying ..."
    - name: Output filename
      run: echo "${{needs.build.outputs.script-file}}"
    - name: Get build artifacts
      uses: actions/download-artifact@v4
      with:
        name: dist-files
    - name: Output Content
      run: ls -l

  report:
    needs: [test, deploy]


